### ISSUE TITLE
API schema has semantic errors

### ISSUE THREAD

**Issue by philmarland** [PagerDuty/api-schema#108]
When trying to parse the OpenAPI 3 schema for the main API using various tools, schema errors are generated.

For example https://editor.swagger.io/ returns the following errors when pointed at https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json.

> Semantic error at components.responses.ArgumentError.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 523
> 
> Semantic error at components.responses.Conflict.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 530
> 
> Semantic error at components.responses.Forbidden.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 541
> 
> Semantic error at components.responses.InternalServerError.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 548
> 
> Semantic error at components.responses.NotAllowed.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 557
> 
> Semantic error at components.responses.NotFound.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 564
> 
> Semantic error at components.responses.TooManyRequests.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 571
> 
> Semantic error at components.responses.PaymentRequired.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 583
> 
> Semantic error at components.responses.Unauthorized.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 595
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.4.name
> Path parameter "alert_id" must have the corresponding {alert_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6731
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.4.name
> Path parameter "alert_id" must have the corresponding {alert_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6731
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.4.name
> Path parameter "rule_id" must have the corresponding {rule_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6731
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.4.name
> Path parameter "rule_id" must have the corresponding {rule_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6731
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.4.name
> Path parameter "rule_id" must have the corresponding {rule_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6731
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.5.name
> Path parameter "rule_id" must have the corresponding {rule_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6732
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.5.name
> Path parameter "rule_id" must have the corresponding {rule_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6732
> 
> Semantic error at paths./escalation_policies/{id}/audit/records.get.parameters.5.name
> Path parameter "rule_id" must have the corresponding {rule_id} segment in the "/escalation_policies/{id}/audit/records" path
> Jump to line 6732
> 
> Semantic error at paths./incidents.put.responses.413.content.application/json.schema.$ref
> $refs must reference a valid location in the document
> Jump to line 7813
> 
> Semantic error at paths./services/{id}/rules.post.requestBody.content.application/json.schema.properties.rule.allOf.1.properties.actions.$ref
> $refs must reference a valid location in the document
> Jump to line 14746

When given the same input, NSwagStudio outputs the following error:

> System.InvalidOperationException: Could not resolve the path '#/paths/~1tags/get/parameters/0'.

I would have expected the schema to be processed successfully using OpenAPI v3 compatible tools.

**Comment by dobs** [comment]
Thanks for bringing this to our attention @philmarland! I've pushed an update that resolves some of the errors you ran into and am investigating the remaining ones.

Once those changes are in I might need some help testing NSwagStudio -- the path for that error appears to be valid but some tools have different JSON pointer expectations.

**Comment by philmarland** [comment]
Thanks! The new version clears the first group of errors (components.*). Just the paths.* ones left I think.

The NSwagStudio error hasn't changed from before just yet.

**Comment by philmarland** [comment]
Hi @dobs, any update on this issue? If it's likely to be some time before it can be addressed that's no problem - I can find a work around - just keen to know if I should hold off as it'd be preferable to generate my API client vs other options. Thanks in advance!

**Comment by dobs** [comment]
Hey @philmarland! Sorry for the delay following up -- I should have follow up on the escalation-policy-related issues tomorrow.

The NSwagStudio issue may be trickier to resolve but I'll see about spending some time on it tomorrow as well -- worst case there may be a transformation to the schema that'll make its JSON pointer support happy.

**Comment by philmarland** [comment]
Thanks @dobs. The NSwag stuff is less important. It's a nice tool but I'm happy to use the tools on the Swagger site as I imagine that's the most consistent / core implementation of OpenAPI at this time. Do let me know if there's anything I can assist with re testing though. Appreciate the support.

**Comment by philmarland** [comment]
That would be fantastic. I only need to work with services and extensions at this time as I'm working on a way to make it easier to manage extensions for a large number of services.

**Comment by bzmw** [comment]
Hey @philmarland , the latest update should fix this issue. Can you give it a shot? https://github.com/PagerDuty/api-schema/pull/119

**Comment by philmarland** [comment]
Hi @bzmw. Thanks for the update. I gave that a go but it crashed Firefox when I tried to generate a .NET client using https://editor.swagger.io/ and Chrome just didn't respond. Both show tonnes of errors in the webdev console. This is weird as I've used this many times to view and manage OpenAPI/Swagger docs and generate servers and clients.

It is quite a large API doc - I wonder if that's related.

NSwagStudio also still gives errors.

Not really sure on the best way to proceed as I can see this appears to be a tool issue rather than a PagerDuty API issue.

**Comment by bzmw** [comment]
Hey @philmarland , I put together a really reduced version that includes only:
 - services
 - extensions
 - vendors

I tried this on editor.swagger.io and it worked. Hopefully it gets you where you need to be!

[Custom-Public.json.zip](https://github.com/PagerDuty/api-schema/files/5404087/Custom-Public.json.zip)

**Comment by philmarland** [comment]
Perfect, thank you! That means I can generate the client I wanted. I hope it'll be possible to access the full API in future but that definitely gets things moving for me for now.

**Comment by philmarland** [comment]
Out of interest, do you think this issue is specific to certain tools then? I'm curious about how consistent the OpenAPI specification (formerly known as the Swagger specification) is with respect to tools / libraries as we're considering these issues on our own projects. It's great you chose to use an open standard for your API, but are these issues you don't / haven't come across with other ecosystems like Go, Python and JavaScript?

**Comment by bzmw** [comment]
I think this is an issue with the specific tool, more specifically it's likely an issue with a specific library that this tool is using.
I have found that support for the standard is about rough in some complicated cases, specifically with huge specs like we have we encounter issues like this a lot. The `$ref` support is particularly bad in the OpenAPI ecosystem.

However! I think the spec is great and support is getting better and better. Make sure to open bugs against tools when you find them there's a good group of folks fixing issues.

**Comment by philmarland** [comment]
That's really helpful, thanks. I'll see if I can raise an issue with Swagger. It'll be interesting for them to confirm whether they feel there's an isssue with the API spec in question (Pager Duty) vs recognising an issue with the tool re support for some OpenAPI feature.

I'm less surprised that NSwagStudio has issues as that's a much less widely-used tool and might just be a case of them not keeping fully up to date with the standard. The Swagger editor though is really popular and Swagger themselves originated the whole OpenAPI standard so it'll be good to get to the bottom of it all.

**Comment by bzmw** [comment]
Awesome, thanks!

I'm going to close this now, if you have any updates feel free to re-open!

**Comment by philmarland** [comment]
I had a go using the cut-down schema document but unfortunately although it doesn't have any parsing errors for the spec, it still looks like Swagger is generating a pretty much garbage client library from it. It's a shame - I was hoping this would be a good way to create a client library and get started quickly but it seems like a dead-end.

I've given it a go using other tools like NSwag and OpenAPI client generators built into Visual Studio, but they all fail also using both the full and cut-down spec file.

I think I'm going to resort to just making HTTP calls the long way, which is a shame as the API appears to be documented but it just doesn't seem compatible with any tools I can find. If anyone reading this has found a suitable workaround for consuming the Pager Duty API from a .NET Core project I'd be all ears!
